### ISSUE TITLE
Cannot read property "includes" of undefined

### ISSUE THREAD

**Issue by UnforeseenOcean** [azu/har-extractor#6]
Suggestion: "Ignore Errors", or "Syntax Error at Line xx" support.
![IMG1615908095](https://user-images.githubusercontent.com/11834016/111334253-c0b21c00-86b6-11eb-9e37-c68264d07219.png)

Also attached is the HAR file so you can test it.

[seventow.zip](https://github.com/azu/har-extractor/files/6150110/seventow.zip)

**Comment by azu** [comment]
Thanks for  report!

Fixed in https://github.com/azu/har-extractor/releases/tag/v1.1.1
